identifier = {
  coreidentifier ~ qualifiers?
}

coreidentifier = {
  ^"swh" ~ ":" ~ schemeversion ~ ":" ~ objecttype ~ ":" ~ objectid
}

qualifiers = {
  ";" ~ qualifier ~ qualifiers?
}

schemeversion = {
  "1"
}

objecttype = {
  ^"snp"
  | ^"rel"
  | ^"rev"
  | ^"dir"
  | ^"cnt"
}

objectid = {
  (HEXDIG){40}
}

qualifier = {
  contextqualifier
  | fragmentqualifier
}

HEXDIG = {
  DIGIT
  | ^"A"
  | ^"B"
  | ^"C"
  | ^"D"
  | ^"E"
  | ^"F"
}

contextqualifier = {
  originctxt
  | visitctxt
  | anchorctxt
  | pathctxt
}

fragmentqualifier = {
  ^"lines" ~ "=" ~ range
  | ^"bytes" ~ "=" ~ range
}

DIGIT = {
  '\u{30}'..'\u{39}'
}

originctxt = {
  ^"origin" ~ "=" ~ urlescaped
}

visitctxt = {
  ^"visit" ~ "=" ~ coreidentifier
}

anchorctxt = {
  ^"anchor" ~ "=" ~ coreidentifier
}

pathctxt = {
  ^"path" ~ "=" ~ pathabsoluteescaped
}

range = {
  number ~ ("-" ~ number)?
}

urlescaped = {
  IRI
}

pathabsoluteescaped = {
  absolute_IRI
}

number = {
  (DIGIT)+
}

IRI = {
  scheme ~ ":" ~ ihier_part ~ ("?" ~ iquery)? ~ ("#" ~ ifragment)?
}

absolute_IRI = {
  scheme ~ ":" ~ ihier_part ~ ("?" ~ iquery)?
}

scheme = {
  ALPHA ~ (ALPHA | DIGIT | "+" | "-" | ".")*
}

ihier_part = {
  "//" ~ iauthority ~ ipath_abempty
  | ipath_absolute
  | ipath_rootless
  | ipath_empty
}

iquery = {
  (ipchar | iprivate | "/" | "?")*
}

ifragment = {
  (ipchar | "/" | "?")*
}

ALPHA = {
  '\u{41}'..'\u{5a}'
  | '\u{61}'..'\u{7a}'
}

iauthority = {
  (iuserinfo ~ "@")? ~ ihost ~ (":" ~ port)?
}

ipath_abempty = {
  ("/" ~ isegment)*
}

ipath_absolute = {
  "/" ~ (isegment_nz ~ ("/" ~ isegment)*)?
}

ipath_rootless = {
  isegment_nz ~ ("/" ~ isegment)*
}

ipath_empty = {
  (. { error(`Can't convert prose description to pest grammar: "ipchar"`) })
}

ipchar = {
  iunreserved
  | pct_encoded
  | sub_delims
  | ":"
  | "@"
}

iprivate = {
  '\u{e000}'..'\u{f8ff}'
  | '\u{f0000}'..'\u{ffffd}'
  | '\u{100000}'..'\u{10fffd}'
}

iuserinfo = {
  (iunreserved | pct_encoded | sub_delims | ":")*
}

ihost = {
  IP_literal
  | IPv4address
  | ireg_name
}

port = {
  DIGIT*
}

isegment = {
  ipchar*
}

isegment_nz = {
  ipchar+
}

iunreserved = {
  ALPHA
  | DIGIT
  | "-"
  | "."
  | "_"
  | "~"
  | ucschar
}

pct_encoded = {
  "%" ~ HEXDIG ~ HEXDIG
}

sub_delims = {
  "!"
  | "$"
  | "&"
  | "'"
  | "("
  | ")"
  | "*"
  | "+"
  | ","
  | ";"
  | "="
}

IP_literal = {
  "[" ~ (IPv6address | IPvFuture) ~ "]"
}

IPv4address = {
  dec_octet ~ "." ~ dec_octet ~ "." ~ dec_octet ~ "." ~ dec_octet
}

ireg_name = {
  (iunreserved | pct_encoded | sub_delims)*
}

ucschar = {
  '\u{a0}'..'\u{d7ff}'
  | '\u{f900}'..'\u{fdcf}'
  | '\u{fdf0}'..'\u{ffef}'
  | '\u{10000}'..'\u{1fffd}'
  | '\u{20000}'..'\u{2fffd}'
  | '\u{30000}'..'\u{3fffd}'
  | '\u{40000}'..'\u{4fffd}'
  | '\u{50000}'..'\u{5fffd}'
  | '\u{60000}'..'\u{6fffd}'
  | '\u{70000}'..'\u{7fffd}'
  | '\u{80000}'..'\u{8fffd}'
  | '\u{90000}'..'\u{9fffd}'
  | '\u{a0000}'..'\u{afffd}'
  | '\u{b0000}'..'\u{bfffd}'
  | '\u{c0000}'..'\u{cfffd}'
  | '\u{d0000}'..'\u{dfffd}'
  | '\u{e1000}'..'\u{efffd}'
}

IPv6address = {
  (h16 ~ ":"){6} ~ ls32
  | "::" ~ (h16 ~ ":"){5} ~ ls32
  | h16? ~ "::" ~ (h16 ~ ":"){4} ~ ls32
  | ((h16 ~ ":")? ~ h16)? ~ "::" ~ (h16 ~ ":"){3} ~ ls32
  | ((h16 ~ ":"){, 2} ~ h16)? ~ "::" ~ (h16 ~ ":"){2} ~ ls32
  | ((h16 ~ ":"){, 3} ~ h16)? ~ "::" ~ h16 ~ ":" ~ ls32
  | ((h16 ~ ":"){, 4} ~ h16)? ~ "::" ~ ls32
  | ((h16 ~ ":"){, 5} ~ h16)? ~ "::" ~ h16
  | ((h16 ~ ":"){, 6} ~ h16)? ~ "::"
}

IPvFuture = {
  ^"v" ~ HEXDIG+ ~ "." ~ (unreserved | sub_delims | ":")+
}

dec_octet = {
  DIGIT
  | '\u{31}'..'\u{39}' ~ DIGIT
  | "1" ~ DIGIT{2}
  | "2" ~ '\u{30}'..'\u{34}' ~ DIGIT
  | "25" ~ '\u{30}'..'\u{35}'
}

h16 = {
  HEXDIG{1, 4}
}

ls32 = {
  (h16 ~ ":" ~ h16)
  | IPv4address
}

unreserved = {
  ALPHA
  | DIGIT
  | "-"
  | "."
  | "_"
  | "~"
}

